### ISSUE TITLE
Set time picker with quarters

### ISSUE THREAD

**Issue by Rasmyta** [marcellosurdi/DateTimePickerComponent#1]
Is it possible to set a time picker with quarters? 
For example:

20:00, 20:15, 20:30, 20.45

**Comment by marcellosurdi** [comment]
No, it currently supports only half hours. Added to todo list

**Comment by energima** [comment]
How we can takeout the datetimeoutput selection to a var to use it into a JS script? 
Thx for help very nice date time picker

**Comment by marcellosurdi** [comment]
> How we can takeout the datetimeoutput selection to a var to use it into a JS script?
> Thx for help very nice date time picker

The selected date is always returned to the value attribute of the input.date_output according to settings.date_output property. Please read [How does this component work](https://github.com/marcellosurdi/DateTimePickerComponent#how-does-this-component-work) section. Thank you for your comment

**Comment by marcellosurdi** [comment]
Hi @Rasmyta,
I worked on your request. See [this branch](https://github.com/marcellosurdi/DateTimePickerComponent/tree/time-picker-enhancement) and the [example 6](https://www.marcellosurdi.name/demo/date-time-picker-component_1.1.0/index.html#example6) of corresponding demo.

Now `settings.round_to` property enables the time picker with select elements. Minutes are rounded to the `round_to` value and his multiples.

Feel free to tell me what you think. I'll merge branches soon

**Comment by marcellosurdi** [comment]
Pull request #2 closes this issue
