### ISSUE TITLE
min_range_hours set to 0 treated as 1

### ISSUE THREAD

**Issue by imaginethatok** [marcellosurdi/DateTimePickerComponent#3]
I'm able to get it to function as 0 by rounding and selecting 0.01, but 0 does not work in the way I would expect.

**Comment by marcellosurdi** [comment]
The min_range_hours property does not expect 0 as a value, the minimum range expressed in hours can't be zero. Why should you set 0 for a range? Here's the code that handles your input:

```
this.min_range = ( settings.min_range_hours ) ? ( settings.min_range_hours * 60 * 60 * 1000 ) : ( 1 * 60 * 60 * 1000 );
```
