### ISSUE TITLE
September appears as SET, October appears as SEP in demo

### ISSUE THREAD

**Issue by imaginethatok** [marcellosurdi/DateTimePickerComponent#4]
https://www.marcellosurdi.name/demo/date-time-picker-component_1.1.2/index.html

**Comment by marcellosurdi** [comment]
You're right, I fixed it! Thanks

**Comment by steveb85** [comment]
i must have old files in our app, and just found this bug and fixed it, and was about to report it, when i found this! love the plugin, thanks for keeping it up!
