### ISSUE TITLE
target for event listeners

### ISSUE THREAD

**Issue by imaginethatok** [marcellosurdi/DateTimePickerComponent#5]
I didn't see this in the documentation: is there a preferred spot for registering for changes in the selected date? The "type" on the input is "hidden" and can't get date changes to trigger.

**Comment by marcellosurdi** [comment]
Hi @imaginethatok, do you need a callback function when a date changes? Did I get it right?

**Comment by imaginethatok** [comment]
@marcellosurdi yes - that is what I'm looking for. The use case is a time-keeping function where selecting a past day will display any time logged on that day:
`document.querySelector( 'div#select_timer_date input.date_output' ).addEventListener('change', updateValue);`

**Comment by marcellosurdi** [comment]
What about if I provide you with a way to execute your custom `function( new_date, old_date )` when a date changes? `new_date` and `old_date` variables would be `Date` objects. Does this solution meet your needs?
```
new DatePicker( 'select_date_2', {
  first_date: "2030-01-02",
  start_date: "2030-01-05",
  last_date: new Date( 2030, 0, 29 ),
  first_day_no: 1,
  date_output: "timestamp",
  change_handler: function( new_date, old_date ) { /* your code */ },
  styles: {
    active_background: '#e34c26',
    active_color: '#fff'
  }
} );
```

**Comment by imaginethatok** [comment]
That would work beautifully.

**Comment by marcellosurdi** [comment]
Hi @imaginethatok,
try the code in [this branch](https://github.com/marcellosurdi/DateTimePickerComponent/tree/change-callback-enhancement), [here](https://www.marcellosurdi.name/demo/date-time-picker-compoment_new/) the demo (see the Example 6).
It should work, let me know!

**Comment by imaginethatok** [comment]
It worked beautifully -- sorry for taking so long to confirm.

**Comment by aalepis** [comment]
Hi, this enhancement would come in handy for me as well! :)

**Comment by marcellosurdi** [comment]
> It worked beautifully -- sorry for taking so long to confirm.
 No problem ;-)

> Hi, this enhancement would come in handy for me as well! :)
I'm very happy :-)

**Comment by robertgodfrey** [comment]
Why wasn't this one ever merged to master? Seems very useful!
