### ISSUE TITLE
Dynamically change date 

### ISSUE THREAD

**Issue by wktdev** [marcellosurdi/DateTimePickerComponent#7]
I want to change the date dynamically with JS. I can't for the life of me figure out how to do this.

I read another issue and the author seems to be asking for a similar thing.

Again, I don't want to change the date by having the user select it, I want to change the date by running a function.

```
calendar = new DateTimePicker("select_datetime", {
          // settings
      },
    });

let date = Date.now();
calendar.changeDate(date)   <---- simple style update.
```

Sorry if this is doable and right in front of my face, but I can't figure it out.
Thanks!

**Comment by marcellosurdi** [comment]
Hi, it's not possible at the moment. I would like to do it.
